[package]
name = "corten"
version = "0.1.102"
authors = ["Tony Bark"]
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
rbtag = "0.3"
nom = "4.2"
metacrate = { git = "https://github.com/tonytins/metacrate" }